#### Q4. We will work with Part 1 folder in the lemm_stop folder. Show the code snippet to get marks for this question.

1. How many documents are marked as spam and not spam? How did you come up with the number?
2. How many words are there in all the documents?
3. What are the top 5 frequent words in the spam documents?
4. What are the top 5 frequent words in the non-spam documents?
5. What is the maximum number of words in a document?
6. What is the minimum number of words in a document?

In [1]:
#4.1
directory = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part1'
import re
import os

emails = os.listdir(directory)
keyword = "spmsg"
spam_count = 0
non_spam_count = 0
spam_docs = []
non_spam_docs = []
for each_email in emails:
    if keyword in each_email:
        spam = each_email
        spam_docs.append(spam)
        spam_count = spam_count + 1
    else:
        non_spam = each_email
        non_spam_docs.append(non_spam)
        non_spam_count = non_spam_count + 1

print("No. of documents that're spams: ", spam_count)
print("No. of documents that're not spams: ", non_spam_count)
print("These are the spam documents: ", spam_docs)

No. of documents that're spams:  48
No. of documents that're not spams:  241
These are the spam documents:  ['spmsga114.txt', 'spmsga100.txt', 'spmsga128.txt', 'spmsga12.txt', 'spmsga13.txt', 'spmsga129.txt', 'spmsga101.txt', 'spmsga115.txt', 'spmsga103.txt', 'spmsga117.txt', 'spmsga11.txt', 'spmsga10.txt', 'spmsga116.txt', 'spmsga102.txt', 'spmsga106.txt', 'spmsga112.txt', 'spmsga14.txt', 'spmsga113.txt', 'spmsga107.txt', 'spmsga139.txt', 'spmsga111.txt', 'spmsga105.txt', 'spmsga104.txt', 'spmsga110.txt', 'spmsga138.txt', 'spmsga141.txt', 'spmsga140.txt', 'spmsga1.txt', 'spmsga135.txt', 'spmsga121.txt', 'spmsga109.txt', 'spmsga108.txt', 'spmsga120.txt', 'spmsga134.txt', 'spmsga122.txt', 'spmsga136.txt', 'spmsga137.txt', 'spmsga123.txt', 'spmsga127.txt', 'spmsga133.txt', 'spmsga132.txt', 'spmsga126.txt', 'spmsga118.txt', 'spmsga130.txt', 'spmsga124.txt', 'spmsga125.txt', 'spmsga131.txt', 'spmsga119.txt']


In [2]:
#4.2
from collections import Counter

def create_dict(directory):
    emails = [os.path.join(directory,f) for f in os.listdir(directory)]
    all_words = []
    for email in emails:
        with open(email, 'r') as m: 
            for i,line in enumerate(m):
                if i == 2: 
                    words = line.split()
                    all_words += words
    dictionary1 = Counter(all_words)
    
    #extracting only words from the dictionary
    keys = dictionary1.keys()
    for item in all_words:
        if item.isalpha() == False: 
            del dictionary1[item]
        elif len(item) == 1:
            del dictionary1[item]
    
    return dictionary1


In [3]:
directory = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part1'
create_dict(directory)


Counter({'first': 108,
         'announcement': 11,
         'groningen': 10,
         'assembly': 2,
         'language': 520,
         'acquisition': 31,
         'university': 296,
         'netherland': 19,
         'september': 21,
         'conference': 73,
         'aim': 10,
         'bring': 21,
         'together': 16,
         'researcher': 9,
         'discuss': 20,
         'merit': 4,
         'constraint': 15,
         'different': 77,
         'theoretical': 33,
         'approach': 34,
         'particular': 37,
         'generative': 14,
         'linguistics': 151,
         'constructionism': 1,
         'dynamic': 5,
         'system': 59,
         'model': 27,
         'connectionism': 3,
         'invite': 27,
         'speaker': 54,
         'harald': 2,
         'clahsen': 2,
         'essex': 3,
         'annette': 1,
         'karmiloff': 1,
         'smith': 3,
         'mrc': 1,
         'cog': 4,
         'dev': 1,
         'unit': 9,
         'london': 25,

In [4]:
directory = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part1'
words = create_dict(directory)
c = 0
for key in words:
    c = c+1
print("There are total ", c, "words in all the documents.")


There are total  9963 words in all the documents.


In [5]:
#4.3
#finding top 5 frequent words in spam documents

emails = [os.path.join(directory,f) for f in os.listdir(directory)]
keyword="spmsga"
all_words = []
for email in emails:
    if keyword in email:
        with open(email, 'r') as m: 
            for i,line in enumerate(m):
                if i == 2: 
                    words = line.split()
                    all_words += words
dictionary2 = Counter(all_words)
    
    #extracting only words from the dictionary
keys = dictionary2.keys()
for item in all_words:
    if item.isalpha() == False: 
        del dictionary2[item]
    elif len(item) == 1:
        del dictionary2[item]
dictionary2 = dictionary2.most_common(5)
dictionary2


[('email', 177),
 ('order', 156),
 ('address', 142),
 ('report', 128),
 ('mail', 122)]

In [6]:
#4.4
#top 5 frequent words in non-spam documents

emails = [os.path.join(directory,f) for f in os.listdir(directory)]
keyword="spmsga"
all_words = []
for email in emails:
    if keyword not in email:
        with open(email, 'r') as m: 
            for i,line in enumerate(m):
                if i == 2: 
                    words = line.split()
                    all_words += words
dictionary3 = Counter(all_words)
    
    #extracting only words from the dictionary
keys = dictionary3.keys()
for item in all_words:
    if item.isalpha() == False: 
        del dictionary3[item]
    elif len(item) == 1:
        del dictionary3[item]
dictionary3 = dictionary3.most_common(5)
dictionary3

[('language', 520),
 ('university', 294),
 ('de', 253),
 ('linguistic', 234),
 ('one', 215)]

In [7]:
#4.5
#finding no. of words in a document
emails = [os.path.join(directory,f) for f in os.listdir(directory)]
all_words = []
words_length = []
for email in emails:
    with open(email, 'r') as m: 
        for i,line in enumerate(m):
            if i == 2: 
                words = line.split()
                for item in words: #removing non-alphabets and punctuations
                    if item.isalpha() == False: 
                        words.remove(item)
                    elif len(item) == 1:
                        words.remove(item)
                words_length.append(len(words))
                
print(words_length)
print("Maximum no. of words in a document is: ", max(words_length))
print("Minimum no. of words in a document is: ", min(words_length))
                

[172, 289, 76, 29, 136, 253, 25, 58, 43, 135, 45, 217, 39, 34, 164, 29, 251, 2393, 204, 484, 33, 295, 25, 386, 667, 10, 958, 393, 53, 156, 895, 372, 42, 161, 208, 73, 444, 392, 89, 70, 31, 45, 48, 17, 684, 133, 231, 405, 116, 46, 271, 895, 604, 51, 215, 230, 666, 120, 144, 75, 61, 707, 92, 140, 177, 436, 32, 107, 68, 132, 51, 40, 187, 701, 113, 106, 240, 10, 31, 104, 11, 140, 43, 95, 58, 225, 68, 57, 92, 191, 875, 116, 123, 1618, 275, 339, 582, 471, 202, 398, 177, 97, 55, 106, 225, 47, 157, 577, 44, 153, 117, 80, 33, 95, 545, 114, 85, 13, 454, 80, 199, 51, 691, 22, 298, 40, 544, 562, 85, 456, 98, 309, 186, 205, 116, 178, 139, 7, 105, 471, 135, 75, 421, 115, 393, 181, 144, 200, 243, 398, 84, 77, 68, 29, 84, 30, 231, 124, 59, 79, 242, 54, 12, 124, 669, 464, 66, 327, 12, 51, 584, 43, 41, 124, 13, 362, 11, 317, 558, 68, 51, 48, 484, 72, 2715, 40, 99, 262, 106, 217, 68, 204, 322, 81, 469, 119, 111, 66, 846, 439, 730, 27, 316, 1008, 712, 206, 53, 183, 42, 248, 80, 191, 289, 104, 22, 96, 32, 

#### Q5. Create a feature extractor function similar to document_features in the NLTK example. Don’t copy the code from NLTK book. Use the feature extractor function to create a training dataset on Part 1 of the data. Train a Naive Bayes classifier as shown in the book chapter.

In [8]:
#5.
#Creating a dictionary of words in the emails

dictionary = [] #globalizing variable

def make_dictionary(train_dir):
    emails = [os.path.join(train_dir,f) for f in os.listdir(train_dir)]    
    all_words = []       
    for mail in emails:    
        with open(mail) as m:
            for i,line in enumerate(m):
                if i == 2:  #Body of email is 3rd line of text file
                    words = line.split()
                    all_words += words
                    for item in all_words: #removing non-alphabets and punctuations
                        if item.isalpha() == False: 
                            all_words.remove(item)
                        elif len(item) == 1:
                            all_words.remove(item)
    
    dictionary = Counter(all_words)
    dictionary = dictionary.most_common(3000)

    return dictionary


In [9]:
#5.
#features extractor - converts words in the emails to word count vectors (the feature).. 
#..and returns a full matrix of vectors

import numpy as np

def document_features(mail_dir): 
    emails = [os.path.join(mail_dir,f) for f in os.listdir(mail_dir)]
    features_matrix = np.zeros((len(emails),3000))
    doc_id = 0;
    for email in emails:
        with open(email) as f:
            for i,line in enumerate(f):
                if i == 2:
                    words = line.split()
                    for word in words:
                        word_id = 0
                        for i,d in enumerate(dictionary):
                            if d[0] == word:
                                word_id = i
                                features_matrix[doc_id, word_id] = words.count(word)
            doc_id = doc_id + 1     
    return features_matrix

mail_dir = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part1'
all_arrays = document_features(mail_dir)
print(all_arrays)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
#5. Shape of the features_matrix
all_arrays.shape

(289, 3000)

In [11]:
#5.
#Preparing training data and labels

from sklearn.naive_bayes import MultinomialNB

# Calling the make_dictionary function
train_dir = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part1'
dictionary = make_dictionary(train_dir)

# Preparing feature vectors per training email and its labels

train_labels = np.zeros(289)
train_labels[241:289] = 1 #48 spam emails - file no. 241-289
train_matrix = document_features(train_dir)

In [12]:
#5.
# Training the Naive bayes classifier

model1 = MultinomialNB()
model1.fit(train_matrix,train_labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

#### Q6. For testing, we will use Part 10 in the lemm_stop folder. Follow similar steps as above to create a test dataset. Apply the feature extractor function to extract features from the test dataset. What is its accuracy on the test dataset? Show the code. What happens if you test on the training dataset? If you get accuracies below 50%, then, there is a bug in your code.

In [13]:
#6.
# Testing the unseen emails for Spam

test_dir = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part10'
test_matrix = document_features(test_dir)
test_labels = np.zeros(291)
test_labels[242:291] = 1 #49 spam emails - files 242-291
result1 = model1.predict(test_matrix)
result_on_train_data = model1.predict(train_matrix)

from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, result1))
print(accuracy_score(train_labels, result_on_train_data))


0.8281786941580757
0.9342560553633218


#### Q7. Evaluation: What is the Precision, Recall, and F-score of the classifier that you trained? Read section 3 of the chapter to answer these questions.

In [14]:
#7.
#Metrics on the test data - Naive Bayes
from sklearn import metrics
target_labels = ['spam_NaiveBayes','nonspam_NaiveBayes']
print(metrics.classification_report(test_labels,result1, target_names=target_labels))


                    precision    recall  f1-score   support

   spam_NaiveBayes       0.85      0.96      0.90       242
nonspam_NaiveBayes       0.47      0.16      0.24        49

          accuracy                           0.83       291
         macro avg       0.66      0.56      0.57       291
      weighted avg       0.79      0.83      0.79       291



#### Q8. Can you try another classifier such as Logistic Regression? How do the evaluation metrics look like? 

In [15]:
#8.
#Training the logistic regression classifier

from sklearn.linear_model import LogisticRegression

model2 = LogisticRegression()
model2.fit(train_matrix,train_labels)


/Users/shristidhakal/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
#9.
# Testing the unseen emails for Spam

test_dir = '/Users/shristidhakal/Documents/Grad School/Comp Linguistics/week 9/lingspam_public/lemm_stop/part10'
test_matrix = document_features(test_dir)
test_labels = np.zeros(291)
test_labels[242:291] = 1 #49 spam emails - files 242-291
result2 = model2.predict(test_matrix)

In [17]:
#9. #Metrics on the test data - Logistic Regression
print(accuracy_score(test_labels, result2))
print('\n')

target_labels2 = ['spam_LogisticReg','nonspam_LogisticReg']
print(metrics.classification_report(test_labels,result2, target_names=target_labels2))

0.7250859106529209


                     precision    recall  f1-score   support

   spam_LogisticReg       0.83      0.85      0.84       242
nonspam_LogisticReg       0.14      0.12      0.13        49

           accuracy                           0.73       291
          macro avg       0.48      0.48      0.48       291
       weighted avg       0.71      0.73      0.72       291

